name: "lstm_word"

model_params:
  type: 'LSTM'
  w_emsize: 300
  nhid: 200
  nlayers: 2
  dropout: 0.2
  pretrained_embeds: 'glove.6B.300d'

train_params:
  epochs: 40
  batch_size: 20
  lr: 0.05
  lr_scheduler: StepLR
  clip: 0.25
