name: "trm_mix"

model_params:
  d_model: 300
  d_hid: 200
  w_emsize: 300
  nlayers: 2
  nhead: 2
  dropout: 0.2
  pretrained_embeds: 'glove.6B.300d'

train_params:
  epochs: 20
  batch_size: 20
  lr: 0.50
  lr_scheduler: StepLR
  clip: 0.5
